// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://saeofugyscjfgqqnqowk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhZW9mdWd5c2NqZmdxcW5xb3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTA1ODYsImV4cCI6MjA3MjM2NjU4Nn0.92yIPYoeF3zCMt6UbOTuBmVIWKMs9UI6Xd51Q4dORKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});